-- MySQL Script generated by MySQL Workbench
-- Fri Jun  7 19:18:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema neuralbeats
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema neuralbeats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `neuralbeats` DEFAULT CHARACTER SET utf8 ;
USE `neuralbeats` ;

-- -----------------------------------------------------
-- Table `neuralbeats`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neuralbeats`.`Korisnik` (
  `idKorinika` INT(11) NOT NULL AUTO_INCREMENT,
  `Password_hash` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Administrator` BIT(1) NULL DEFAULT NULL,
  `Opis` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`idKorinika`),
  UNIQUE INDEX `username_UNIQUE` (`Username` ASC) ,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `neuralbeats`.`Prati`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neuralbeats`.`Prati` (
  `Prati` INT NOT NULL,
  `Pracen` INT NOT NULL,
  PRIMARY KEY (`Prati`, `Pracen`),
  INDEX `Pracen_idx` (`Pracen` ASC) ,
  CONSTRAINT `Prati`
    FOREIGN KEY (`Prati`)
    REFERENCES `neuralbeats`.`Korisnik` (`idKorinika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Pracen`
    FOREIGN KEY (`Pracen`)
    REFERENCES `neuralbeats`.`Korisnik` (`idKorinika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `neuralbeats`.`Blokiranje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neuralbeats`.`Blokiranje` (
  `Blokirao` INT(11) NOT NULL,
  `Blokiran` INT(11) NOT NULL,
  PRIMARY KEY (`Blokirao`, `Blokiran`),
  INDEX `blokiran_idx` (`Blokiran` ASC) ,
  INDEX `blokirao_idx` (`Blokirao` ASC) ,
  CONSTRAINT `blokiran`
    FOREIGN KEY (`Blokiran`)
    REFERENCES `neuralbeats`.`Korisnik` (`idKorinika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `blokirao`
    FOREIGN KEY (`Blokirao`)
    REFERENCES `neuralbeats`.`Korisnik` (`idKorinika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `neuralbeats`.`Muzika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neuralbeats`.`Muzika` (
  `idMuzike` INT(11) NOT NULL AUTO_INCREMENT,
  `Autor` INT(11) NOT NULL,
  `Naslov` VARCHAR(100) NOT NULL,
  `Opis` VARCHAR(1000) NULL DEFAULT NULL,
  `Vreme` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idMuzike`),
  INDEX `autor_idx` (`Autor` ASC),
  CONSTRAINT `autor`
    FOREIGN KEY (`Autor`)
    REFERENCES `neuralbeats`.`Korisnik` (`idKorinika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `neuralbeats`.`Poruka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neuralbeats`.`Poruka` (
  `idPoruke` INT(11) NOT NULL AUTO_INCREMENT,
  `Posiljalac` INT(11) NOT NULL,
  `Sadrzaj` VARCHAR(1000) NULL DEFAULT NULL,
  `Vreme` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idPoruke`),
  INDEX `posiljalac_idx` (`Posiljalac` ASC),
  CONSTRAINT `posiljalac`
    FOREIGN KEY (`Posiljalac`)
    REFERENCES `neuralbeats`.`Korisnik` (`idKorinika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `neuralbeats`.`Komentar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neuralbeats`.`Komentar` (
  `zaMuziku` INT(11) NOT NULL,
  `idKomentara` INT(11) NOT NULL,
  INDEX `zaMuziku_idx` (`zaMuziku` ASC),
  PRIMARY KEY (`idKomentara`),
  CONSTRAINT `zaMuziku`
    FOREIGN KEY (`zaMuziku`)
    REFERENCES `neuralbeats`.`Muzika` (`idMuzike`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idKomentara`
    FOREIGN KEY (`idKomentara`)
    REFERENCES `neuralbeats`.`Poruka` (`idPoruke`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `neuralbeats`.`Licna_poruka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neuralbeats`.`Licna_poruka` (
  `Primalac` INT(11) NOT NULL,
  `idLicne_Poruke` INT(11) NOT NULL,
  INDEX `primalac_idx` (`Primalac` ASC),
  PRIMARY KEY (`idLicne_Poruke`),
  CONSTRAINT `primalac`
    FOREIGN KEY (`Primalac`)
    REFERENCES `neuralbeats`.`Korisnik` (`idKorinika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idLicnePoruke`
    FOREIGN KEY (`idLicne_Poruke`)
    REFERENCES `neuralbeats`.`Poruka` (`idPoruke`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
